# .github/labeler.yml
01-tutorials:
  - "01-tutorials/**"
02-use-cases:
  - "02-use-cases/**"
03-integrations:
  - "03-integrations/**"
01-AgentCore-runtime:
  - "01-tutorials/01-AgentCore-runtime/**"
02-AgentCore-gateway:
  - "01-tutorials/02-AgentCore-gateway/**"
03-AgentCore-identity:
  - "01-tutorials/03-AgentCore-identity/**"
04-AgentCore-memory:
  - "01-tutorials/04-AgentCore-memory/**"
05-AgentCore-tools:
  - "01-tutorials/05-AgentCore-tools/**"
06-AgentCore-observability:
  - "01-tutorials/06-AgentCore-observability/**"
07-AgentCore-E2E:
  - "01-tutorials/07-AgentCore-E2E/**"
asynchronous-shopping-assistant:
  - "02-use-cases/asynchronous-shopping-assistant/**"
AWS-operations-agent:
  - "02-use-cases/AWS-operations-agent/**"
customer-support-assistant:
  - "02-use-cases/customer-support-assistant/**"
DB-performance-analyzer:
  - "02-use-cases/DB-performance-analyzer/**"
device-management-agent:
  - "02-use-cases/device-management-agent/**"
healthcare-appointment-agent:
  - "02-use-cases/healthcare-appointment-agent/**"
local-prototype-to-agentcore:
  - "02-use-cases/local-prototype-to-agentcore/**"
SRE-agent:
  - "02-use-cases/SRE-agent/**"
text-to-python-ide:
  - "02-use-cases/text-to-python-ide/**"
video-games-sales-assistant:
  - "02-use-cases/video-games-sales-assistant/**"
bedrock-agent:
  - "03-integrations/bedrock-agent/**"
agentic-frameworks:
  - "03-integrations/agentic-frameworks/**"
